// mod_hooks.h — runner-internal surface for docs/mod-hooks.md.
//
// Two audiences:
//   - Registration: bank hook tables (<bank>_hooks.c, emitted by
//     nds_recompile --hook-seams) register here at startup, the same way a
//     bank's dispatch table registers with nds_register_dispatch. See
//     runtime_hook_enter (declared in runtime_arm.h, defined in
//     mod_hooks.cpp) for the wrapper-side entry point.
//   - The three choke points (runtime_call_should_return, runtime_dispatch_impl,
//     tier3.cpp's per-transfer nds_has_bank() probe) call
//     nds_mod_hooks_check_return() with the transfer's resolved target so an
//     armed return watch can fire. It is a pure observer: it never changes
//     what the choke point does next, only whether a leave handler runs.
#pragma once

#include <cstdio>

#include "nds_mod.h"
#include "runtime_arm.h"

// Registers one bank's hook table (built-in banks with a `<bank>_hooks.c`,
// or a title bank's, gated behind the same ROM SHA-1 check as its dispatch
// table). `bank` must outlive the process -- generated tables always pass a
// string literal. Safe to call only before the machine runs (see nds_mod.h).
void nds_mod_hooks_register_table(const char* bank,
                                  const NdsHookTableEntry* table,
                                  unsigned len);

// Generated by runner/CMakeLists.txt from whichever built-in bank (the
// BIOS/freebios/firmware banks under GEN) actually has a <bank>_hooks.c.
// A no-op body when none do. Call once at startup, alongside the built-in
// dispatch table registration it mirrors.
void nds_mod_register_builtin_hook_tables();

// Per-CPU "any return watch currently armed" flag. The three choke points
// test this directly (one load) before paying for anything else; kept here
// rather than behind a function call so it inlines to nothing when unused.
extern bool g_nds_mod_watch_armed[2];

// The watch-stack search + fire. Only reached when g_nds_mod_watch_armed[cpu]
// is true. `pc` is the transfer's resolved target, already masked the same
// way the choke point itself uses it (mode comes from the CURRENT g_cpu.cpsr
// T bit, exactly as runtime_call_should_return's own key does -- by the time
// any of the three choke points run, cpsr.T already reflects the transfer).
void nds_mod_hooks_check_return_slow(uint32_t pc);

static inline void nds_mod_hooks_check_return(uint32_t pc) {
    if (!g_nds_mod_watch_armed[g_nds_active]) return;
    nds_mod_hooks_check_return_slow(pc);
}

// Exit-time summary (enter calls, handled, leave fired, duplicate-entry
// suppressed, watches evicted/dropped, registrations failed). Prints nothing
// when no hook table was ever registered.
void nds_mod_hooks_report(std::FILE* out);

// Test-only introspection (used by runner/tests/mod_hooks_test.cpp to check
// the watch stack directly rather than re-deriving its depth indirectly).
unsigned nds_mod_hooks_test_watch_depth(int cpu);
void nds_mod_hooks_test_reset();
